services:
  redis_server:
    restart: always
    image: "redis:5.0.10-alpine"
    container_name: agorax_redis_server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  agorax_backend:
    image: agorax_backend_image
    restart: on-failure
    container_name: agorax_backend_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app/web
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: /home/app/web/entrypoint.sh
    depends_on:
      rabbitmq_server:
        condition: service_healthy
      redis_server:
        condition: service_started

  rabbitmq_server:
    restart: always
    image: "rabbitmq:management-alpine"
    container_name: agorax_rabbitmq_server
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  agorax_rabbitmq_worker:
    restart: on-failure
    entrypoint: ["python", "-m", "src.todolist.services.rabbitmq.consumer"]
    image: agorax_backend_image
    container_name: agorax_rabbitmq_worker   
    volumes:
      - .:/home/app/web
    depends_on:
      rabbitmq_server:
        condition: service_healthy
      agorax_backend:
        condition: service_started
      redis_server:
        condition: service_started
    env_file:
      - .env