services:
  redis_server:
    restart: always
    image: "redis:5.0.10-alpine"
    container_name: todolist_redis_server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  todolist_backend:
    image: todolist_backend_image
    restart: on-failure
    container_name: todolist_backend_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app/web
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: /home/app/web/entrypoint.sh
  
  rabbitmq_server:
    restart: always
    image: "rabbitmq:management-alpine"
    container_name: todolist_rabbitmq_server
    env_file:
      - .env

  todolist_rabbitmq_worker:
    restart: on-failure
    entrypoint: ["python", "-m", "src.todolist.services.rabbitmq.consumer"]
    image: todolist_backend_image
    container_name: todolist_rabbitmq_worker   
    volumes:
      - .:/home/app/web
    depends_on:
      - rabbitmq_server
      - todolist_backend
      - redis_server
    env_file:
      - .env